#!/usr/bin/env bash
set -euo pipefail

REAL_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
SCRIPT_DIR="$(cd "$(dirname "${REAL_PATH}")" && pwd)"
EXECUTABLE="${SCRIPT_DIR}/cli.py"

exec uv run --project "${SCRIPT_DIR}" "${EXECUTABLE}" "$@"
