---
model: openrouter/deepseek/deepseek-r1
read: CONVENTIONS.md                                                                                                         
file: TODO.md                                                                                                                            
# The one true path
vim: true                                                                                                                           
