preferences:
  linker_src: $HOME/dotfiles
  linker_dest: $HOME
links:
  - src: .vimsnippets # You can link to multiple destinations
    dest:
      - .vimsnippets
      - .vim/bundle/.dein/stapler-snips
      - .config/coc/ultisnips
  - src: .mixxx/controllers
  - src: bin/scripts/*
    dest: bin/scripts
    os: "Linux Darwin"
  - src: .vimrc
    dest: .config/nvim/init.vim
    os: "Linux Darwin"
  - src: .config/nvim/coc-settings.json
  - src: .config/nixpkgs
    os: "Linux Darwin"
  - src: stapler-scripts/*
    dest: bin/scripts
    os: "Linux Darwin"
  - src: stapler-scripts/PowerShell
    dest: "%userprofile%\\My Documents\\WindowsPowerShell\\"
    os: "Windows"
  - src: .vimrc
    dest: "%userprofile%\\AppData\\Local\\nvim\\init.vim"
    os: "Windows"
    # Symlinks for git are broken on windows
  - src: .gittemplates
    os: "Linux Darwin"
  - src: .vim/spell
  - src: .shell
    os: "Linux Darwin"
  - src: .tmux/*
  - src: .home-manager

ignore:
  # Globbing patterns to ignore when
  # linking config files to home dir
  - "*stapler*"
  - "cfgcaddy"
  - "*.git"
  - "*.swp"
  - "*.yml"
  - "*.zip"
  - "tags"
  - "nerd-fonts"
  - ".gittemplates"
