preferences:
  linker_src: $HOME/dotfiles
  linker_dest: $HOME
links:
  - src: .vimsnippets # You can link to multiple destinations
    dest:
      - .vimsnippets
      - .vim/bundle/.dein/stapler-snips
  - src: .mixxx/controllers
  - src: bin/scripts/*
    dest: bin/scripts
  - src: .vimrc
    dest: .config/nvim/init.vim
  - src: staplerlinker/staplerlinker/cli.py
    dest: bin/bin/staplerlinker
  - src: stapler-scripts/*
    dest: bin/scripts
ignore:
# Globbing patterns to ignore when
# linking config files to home dir
  - "*stapler*"
  - "cfgcaddy"
  - "*.git$"
  - "*.swp"
  - "*.yml"
  - "*.zip"
  - "env"
  - "*.txt"
  - ".ropeproject"
  - "awesome*"
  - "*linker*"
  - "tags"
  - "nerd-fonts"
  - ".customlinks"
