#!/usr/bin/env sh

# vim: ai ts=2 sw=2 et sts=2 ft=sh

ORIGIN_URL=$(git ls-remote --get-url 'origin')

export GIT_AUTHOR_NAME="Tyler Stapler"
export GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME
git config --local user.name "$GIT_AUTHOR_NAME"

case $ORIGIN_URL in
  *github.com/Workiva*|*github.com:Workiva*|\
  *github.com/workiva*|*github.com:workiva*|\
  *github.com/*-wf*|*github.com:*-wf*|\
  *github.com/*-wk*|*github.com:*-wk*)
    export GIT_AUTHOR_EMAIL="tyler.stapler@workiva.com"
	;;
  *.googlesource.com*|sso://*)
    export GIT_AUTHOR_EMAIL="tstapler@google.com"
  ;;
	*)
    export GIT_AUTHOR_EMAIL="tystapler@gmail.com"
	;;
esac

export GIT_COMITTER_EMAIL=$GIT_AUTHOR_EMAIL
git config --local user.email "$GIT_AUTHOR_EMAIL"
