receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  prometheus_remote_write:
    endpoint: http://victoriametrics:8428/api/v1/write
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  otlphttp/victorialogs:
    logs_endpoint: http://victorialogs:9428/insert/opentelemetry/v1/logs
  debug:
    verbosity: basic

service:
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus_remote_write]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/tempo]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/victorialogs, debug]
