# Install programs from source
---
- name: Make sure ~/bin directory exists
  file:
    path=~/bin
    state=directory
  become: no

- name: Install lemonbar from source
  include: lemonbar.yml

- name: Install playerctl from source
  include: playerctl.yml
