#Python Packages - installed from pypi using pip
---
- name: "Install python packages"
  pip: 
    name={{item}} 
    state=present
  with_items:
    - ipdb
    - youtube-dl
    - ansible
    #Vim
    - grip
    - html-tree-diff
    - pandocfilters
