#!/usr/bin/env sh

# vim: ai ts=2 sw=2 et sts=2 ft=sh

# Source shared functions
. "$HOME/dotfiles/stapler-scripts/git_shared.sh"

ORIGIN_URL=$(git ls-remote --get-url 'origin')

export GIT_AUTHOR_NAME="Tyler Stapler"
export GIT_COMMITTER_NAME=$GIT_AUTHOR_NAME
git config --local user.name "$GIT_AUTHOR_NAME"

export GIT_AUTHOR_EMAIL=$(get_git_email "$ORIGIN_URL")
export GIT_COMMITTER_EMAIL=$GIT_AUTHOR_EMAIL
git config --local user.email "$GIT_AUTHOR_EMAIL"
