#!/usr/bin/env bash

INSTALLER_DIR="$HOME/stapler-installer"
DYNAMIC_HOSTFILE="$INSTALLER_DIR/dynamic-inventory.py" 

if [[ -z "$HOSTNAME" ]]; then
  HOSTNAME=$(hostname)
fi

cd "$INSTALLER_DIR" || exit

if [[ "$1" == "all" ]]; then
  sudo echo "Starting installer for all hosts"
  ansible-playbook -i "$DYNAMIC_HOSTFILE" "$INSTALLER_DIR"/ansible/playbooks/install_all_machines.yml "${@:2}"
else
  sudo echo "Starting installer for $HOSTNAME"
  ansible-playbook -i "$DYNAMIC_HOSTFILE" "$(find "$INSTALLER_DIR" -iname "*$HOSTNAME*.yml")" "$@"
fi
