#!/bin/bash
# Discover available Claude models from Anthropic and AWS Bedrock
# and update the LiteLLM config.yaml

set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_FILE="${SCRIPT_DIR}/config.yaml"
BACKUP_FILE="${CONFIG_FILE}.backup"

# Load environment variables
if [ -f "${SCRIPT_DIR}/.env" ]; then
    source "${SCRIPT_DIR}/.env"
fi

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check dependencies
check_dependencies() {
    local missing=()
    command -v aws >/dev/null 2>&1 || missing+=("aws")
    command -v jq >/dev/null 2>&1 || missing+=("jq")
    command -v yq >/dev/null 2>&1 || missing+=("yq")

    if [ ${#missing[@]} -ne 0 ]; then
        log_error "Missing dependencies: ${missing[*]}"
        echo "Install with:"
        echo "  brew install awscli jq yq  # macOS"
        echo "  apt install awscli jq && pip install yq  # Linux"
        exit 1
    fi
}

# Get Anthropic models (hardcoded list since API doesn't list models)
get_anthropic_models() {
    # These are the known Anthropic models
    # Update this list when new models are released
    cat <<EOF
claude-opus-4-5-20251101
claude-sonnet-4-5-20250929
claude-opus-4-20250514
claude-sonnet-4-20250514
claude-3-7-sonnet-20250219
claude-3-5-sonnet-20241022
claude-3-5-haiku-20241022
claude-3-opus-20240229
claude-3-sonnet-20240229
claude-3-haiku-20240307
EOF
}

# Get available Bedrock models
get_bedrock_models() {
    local region="${AWS_REGION:-us-west-2}"

    log_info "Querying Bedrock models in region: $region"

    # List foundation models from Bedrock
    aws bedrock list-foundation-models \
        --region "$region" \
        --by-provider anthropic \
        --query 'modelSummaries[?contains(modelId, `claude`)].modelId' \
        --output text 2>/dev/null | tr '\t' '\n' | sort -u || echo ""
}

# Map Anthropic model to Bedrock model ID
anthropic_to_bedrock() {
    local model="$1"
    local region="${AWS_REGION:-us-west-2}"

    # Map common model names to Bedrock IDs
    case "$model" in
        claude-opus-4-5-20251101)
            echo "us.anthropic.claude-opus-4-5-20251101-v1:0"
            ;;
        claude-sonnet-4-5-20250929)
            echo "us.anthropic.claude-sonnet-4-5-20250929-v1:0"
            ;;
        claude-opus-4-20250514)
            echo "us.anthropic.claude-opus-4-20250514-v1:0"
            ;;
        claude-sonnet-4-20250514)
            echo "us.anthropic.claude-sonnet-4-20250514-v1:0"
            ;;
        claude-3-7-sonnet-20250219)
            echo "us.anthropic.claude-3-7-sonnet-20250219-v1:0"
            ;;
        claude-3-5-sonnet-20241022)
            echo "us.anthropic.claude-3-5-sonnet-20241022-v2:0"
            ;;
        claude-3-5-haiku-20241022)
            echo "us.anthropic.claude-3-5-haiku-20241022-v1:0"
            ;;
        claude-3-opus-20240229)
            echo "us.anthropic.claude-3-opus-20240229-v1:0"
            ;;
        claude-3-sonnet-20240229)
            echo "anthropic.claude-3-sonnet-20240229-v1:0"
            ;;
        claude-3-haiku-20240307)
            echo "us.anthropic.claude-3-haiku-20240307-v1:0"
            ;;
        *)
            echo ""
            ;;
    esac
}

# Check if Bedrock model is available
check_bedrock_model() {
    local model_id="$1"
    local region="${AWS_REGION:-us-west-2}"

    # Try to get model info
    aws bedrock get-foundation-model \
        --model-identifier "$model_id" \
        --region "$region" \
        --query 'modelDetails.modelId' \
        --output text 2>/dev/null && return 0

    return 1
}

# Generate config YAML
generate_config() {
    local anthropic_models=("$@")

    cat <<'HEADER'
# LiteLLM Proxy Configuration
# Auto-generated by update-models.sh
# Primary: Anthropic Direct API
# Fallback: AWS Bedrock (on rate limits or errors)

model_list:
HEADER

    local model_count=0

    for model in "${anthropic_models[@]}"; do
        local bedrock_id=$(anthropic_to_bedrock "$model")
        local model_id=$(echo "$model" | tr '-' '_' | tr '.' '_')

        # Add Anthropic model
        cat <<EOF
  # ${model}
  - model_name: ${model}
    litellm_params:
      model: anthropic/${model}
      api_key: os.environ/ANTHROPIC_API_KEY
    model_info:
      id: anthropic-${model_id}

EOF

        # Add Bedrock model if available
        if [ -n "$bedrock_id" ]; then
            cat <<EOF
  - model_name: ${model}
    litellm_params:
      model: bedrock/${bedrock_id}
      aws_region_name: os.environ/AWS_REGION
    model_info:
      id: bedrock-${model_id}

EOF
        fi

        ((model_count++))
    done

    # Add aliases
    cat <<'ALIASES'
  # ============================================
  # MODEL ALIASES (Convenience names)
  # ============================================
  - model_name: claude-opus
    litellm_params:
      model: anthropic/claude-opus-4-5-20251101
      api_key: os.environ/ANTHROPIC_API_KEY
    model_info:
      id: alias-opus-anthropic

  - model_name: claude-opus
    litellm_params:
      model: bedrock/us.anthropic.claude-opus-4-5-20251101-v1:0
      aws_region_name: os.environ/AWS_REGION
    model_info:
      id: alias-opus-bedrock

  - model_name: claude-sonnet
    litellm_params:
      model: anthropic/claude-sonnet-4-5-20250929
      api_key: os.environ/ANTHROPIC_API_KEY
    model_info:
      id: alias-sonnet-anthropic

  - model_name: claude-sonnet
    litellm_params:
      model: bedrock/us.anthropic.claude-sonnet-4-5-20250929-v1:0
      aws_region_name: os.environ/AWS_REGION
    model_info:
      id: alias-sonnet-bedrock

  - model_name: claude-haiku
    litellm_params:
      model: anthropic/claude-3-5-haiku-20241022
      api_key: os.environ/ANTHROPIC_API_KEY
    model_info:
      id: alias-haiku-anthropic

  - model_name: claude-haiku
    litellm_params:
      model: bedrock/us.anthropic.claude-3-5-haiku-20241022-v1:0
      aws_region_name: os.environ/AWS_REGION
    model_info:
      id: alias-haiku-bedrock

ALIASES

    # Add router and settings
    cat <<'SETTINGS'
# Router settings for fallback behavior
router_settings:
  routing_strategy: simple-shuffle
  num_retries: 2
  timeout: 120
  allowed_fails: 1
  cooldown_time: 60
  retry_after: 5

# LiteLLM settings
litellm_settings:
  num_retries: 3
  request_timeout: 300
  drop_params: true

# General proxy settings
general_settings:
  master_key: os.environ/LITELLM_MASTER_KEY
SETTINGS

    log_info "Generated config with $model_count models"
}

# Main
main() {
    check_dependencies

    log_info "Discovering available Claude models..."

    # Get Anthropic models
    local anthropic_models
    mapfile -t anthropic_models < <(get_anthropic_models)
    log_info "Found ${#anthropic_models[@]} Anthropic models"

    # Get Bedrock models
    local bedrock_models
    mapfile -t bedrock_models < <(get_bedrock_models)
    if [ ${#bedrock_models[@]} -gt 0 ]; then
        log_info "Found ${#bedrock_models[@]} Bedrock models"
    else
        log_warn "Could not query Bedrock models (check AWS credentials)"
    fi

    # Backup existing config
    if [ -f "$CONFIG_FILE" ]; then
        cp "$CONFIG_FILE" "$BACKUP_FILE"
        log_info "Backed up existing config to ${BACKUP_FILE}"
    fi

    # Generate new config
    generate_config "${anthropic_models[@]}" > "$CONFIG_FILE"

    log_info "Config updated: $CONFIG_FILE"
    echo ""
    echo "To apply changes, restart the proxy:"
    echo "  make restart"
}

# Show current models
show_models() {
    log_info "Current models in config:"
    yq '.model_list[].model_name' "$CONFIG_FILE" 2>/dev/null | sort -u || \
        grep 'model_name:' "$CONFIG_FILE" | sed 's/.*model_name: //' | sort -u
}

# Parse arguments
case "${1:-update}" in
    update)
        main
        ;;
    show)
        show_models
        ;;
    bedrock)
        get_bedrock_models
        ;;
    *)
        echo "Usage: $0 {update|show|bedrock}"
        echo ""
        echo "  update  - Discover models and update config.yaml"
        echo "  show    - Show current models in config"
        echo "  bedrock - List available Bedrock models"
        exit 1
        ;;
esac
